
export const fakeData: object[] = [
    {
        id: 1,
        email: 'puddu@email.com',
        name: 'puddu',
        surname: 'mimmo3',
        age: 1,
    },
    {
        id: 2,
        email: 'puddu2@email.com',
        name: 'puddu22',
        surname: 'mimmo2',
        age: 2,
    },
    {
        id: 3,
        email: 'puddu3@email.com',
        name: 'puddu24',
        surname: 'mimmo1',
        age: 3,
    },
    {
        id: 4,
        email: 'puddu4@email.com',
        name: '4442e2',
        surname: 'ewewew',
        age: 4,
    },
    {
        id: 5,
        email: 'puddu5@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 6,
        email: 'puddu6@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 7,
        email: 'puddu7@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 7,
        email: 'puddu7@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 8,
        email: 'puddu8@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 9,
        email: 'puddu9@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 10,
        email: 'puddu5@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 11,
        email: 'puddu5@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 12,
        email: 'puddu5@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
    {
        id: 13,
        email: 'puddu5@email.com',
        name: '4442eee2',
        surname: 'dsadsads',
        age: 12,
    },
];